version: "3.7"

services:
  petland-db:
    image: postgres
    container_name: petland-db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=petland_db
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - 5432:5432
